export interface Question {
  id: string
  letter: string
  question: string
  answer: string
  difficulty: "facil" | "medio" | "dificil"
  category?: string
}

export const questionsDatabase: Question[] = [
  // Agregando todas las preguntas con las difíciles incluidas
  {
    id: "a1",
    letter: "A",
    question: "Conjunto de partículas minerales en la playa",
    answer: "Arena",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "a2",
    letter: "A",
    question: "Animal que vuela y tiene plumas",
    answer: "Ave",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "a3",
    letter: "A",
    question: "Líquido transparente e incoloro esencial para la vida",
    answer: "Agua",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "a4",
    letter: "A",
    question: "Instrumento musical de cuerda pulsada",
    answer: "Arpa",
    difficulty: "medio",
    category: "musica",
  },
  {
    id: "a5",
    letter: "A",
    question: "Capital de Grecia",
    answer: "Atenas",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "dif-a1",
    letter: "A",
    question: "Sustancia que combate infecciones bacterianas",
    answer: "Antibiótico",
    difficulty: "dificil",
    category: "medicina",
  },
  {
    id: "b1",
    letter: "B",
    question: "Sitio poblado de árboles y matas",
    answer: "Bosque",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "b2",
    letter: "B",
    question: "Deporte que se juega con una pelota y dos aros elevados",
    answer: "Baloncesto",
    difficulty: "facil",
    category: "deportes",
  },
  {
    id: "b3",
    letter: "B",
    question: "Embarcación para navegar",
    answer: "Barco",
    difficulty: "facil",
    category: "transporte",
  },
  {
    id: "dif-b1",
    letter: "B",
    question: "Escritor argentino autor de 'El Aleph' y 'Ficciones'",
    answer: "Borges",
    difficulty: "dificil",
    category: "literatura",
  },
  {
    id: "c1",
    letter: "C",
    question: "Bebida fermentada de cebada",
    answer: "Cerveza",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "c2",
    letter: "C",
    question: "Bebida caliente hecha con granos tostados",
    answer: "Café",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "c3",
    letter: "C",
    question: "Vehículo de cuatro ruedas",
    answer: "Coche",
    difficulty: "facil",
    category: "transporte",
  },
  {
    id: "dif-c1",
    letter: "C",
    question: "Tejido flexible que recubre articulaciones y nariz",
    answer: "Cartílago",
    difficulty: "dificil",
    category: "anatomia",
  },
  {
    id: "d1",
    letter: "D",
    question: "Actor estadounidense protagonista de Titanic",
    answer: "DiCaprio",
    difficulty: "dificil",
    category: "espectaculos",
  },
  {
    id: "d2",
    letter: "D",
    question: "Territorio arenoso o pedregoso con escasa vegetación",
    answer: "Desierto",
    difficulty: "facil",
    category: "geografia",
  },
  {
    id: "d3",
    letter: "D",
    question: "Forma de gobierno donde el pueblo elige",
    answer: "Democracia",
    difficulty: "medio",
    category: "politica",
  },
  {
    id: "dif-d1",
    letter: "D",
    question: "Gas formado por carbono y oxígeno presente en respiración y combustión",
    answer: "Dióxido de carbono",
    difficulty: "dificil",
    category: "quimica",
  },
  {
    id: "e1",
    letter: "E",
    question: "Ocultación de un astro por otro",
    answer: "Eclipse",
    difficulty: "facil",
    category: "astronomia",
  },
  {
    id: "e2",
    letter: "E",
    question: "Animal paquidermo con trompa",
    answer: "Elefante",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "e3",
    letter: "E",
    question: "Lugar donde se enseña",
    answer: "Escuela",
    difficulty: "facil",
    category: "educacion",
  },
  {
    id: "dif-e1",
    letter: "E",
    question: "Conjunto de seres vivos y su entorno que interactúan",
    answer: "Ecosistema",
    difficulty: "dificil",
    category: "ciencia",
  },
  {
    id: "f1",
    letter: "F",
    question: "Deporte que se juega con los pies",
    answer: "Fútbol",
    difficulty: "facil",
    category: "deportes",
  },
  {
    id: "f2",
    letter: "F",
    question: "Historia breve con enseñanza moral",
    answer: "Fábula",
    difficulty: "facil",
    category: "literatura",
  },
  {
    id: "f3",
    letter: "F",
    question: "Red social más grande del mundo",
    answer: "Facebook",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "dif-f1",
    letter: "F",
    question: "Proceso por el cual las plantas convierten luz en energía",
    answer: "Fotosíntesis",
    difficulty: "dificil",
    category: "biologia",
  },
  {
    id: "g1",
    letter: "G",
    question: "Animal doméstico que maúlla",
    answer: "Gato",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "g2",
    letter: "G",
    question: "Deporte que se juega con palos y pelota pequeña",
    answer: "Golf",
    difficulty: "facil",
    category: "deportes",
  },
  {
    id: "g3",
    letter: "G",
    question: "Buscador de internet más utilizado",
    answer: "Google",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "dif-g1",
    letter: "G",
    question: "Masa de hielo en movimiento formada por acumulación de nieve",
    answer: "Glaciar",
    difficulty: "dificil",
    category: "geografia",
  },
  {
    id: "h1",
    letter: "H",
    question: "Postre frío hecho con leche y azúcar",
    answer: "Helado",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "h2",
    letter: "H",
    question: "Lugar donde vive una familia",
    answer: "Hogar",
    difficulty: "facil",
    category: "general",
  },
  {
    id: "h3",
    letter: "H",
    question: "Deporte que se juega sobre hielo",
    answer: "Hockey",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "dif-h1",
    letter: "H",
    question: "Proteína de la sangre que transporta oxígeno",
    answer: "Hemoglobina",
    difficulty: "dificil",
    category: "biologia",
  },
  {
    id: "i1",
    letter: "I",
    question: "Aplicación móvil para compartir fotos",
    answer: "Instagram",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "i2",
    letter: "I",
    question: "Lugar donde se reza",
    answer: "Iglesia",
    difficulty: "facil",
    category: "religion",
  },
  {
    id: "i3",
    letter: "I",
    question: "Estación del año más fría",
    answer: "Invierno",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "dif-i1",
    letter: "I",
    question: "Aumento generalizado y sostenido de los precios",
    answer: "Inflación",
    difficulty: "dificil",
    category: "economia",
  },
  {
    id: "j1",
    letter: "J",
    question: "Lugar donde se cultivan plantas",
    answer: "Jardín",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "j2",
    letter: "J",
    question: "Profesión que administra justicia",
    answer: "Juez",
    difficulty: "medio",
    category: "profesiones",
  },
  {
    id: "j3",
    letter: "J",
    question: "Cantante estadounidense 'King of Pop'",
    answer: "Jackson",
    difficulty: "medio",
    category: "espectaculos",
  },
  {
    id: "dif-j1",
    letter: "J",
    question: "Planeta más grande del sistema solar",
    answer: "Júpiter",
    difficulty: "dificil",
    category: "astronomia",
  },
  {
    id: "k1",
    letter: "K",
    question: "Unidad de peso de mil gramos",
    answer: "Kilogramo",
    difficulty: "facil",
    category: "medidas",
  },
  {
    id: "k2",
    letter: "K",
    question: "Arte marcial japonés de golpes con manos y pies",
    answer: "Karate",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "k3",
    letter: "K",
    question: "Aderezo de tomate dulce y ácido",
    answer: "Ketchup",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "dif-k1",
    letter: "K",
    question: "Unidad de longitud equivalente a mil metros",
    answer: "Kilómetro",
    difficulty: "dificil",
    category: "medidas",
  },
  {
    id: "l1",
    letter: "L",
    question: "Animal que ruge en la selva",
    answer: "León",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "l2",
    letter: "L",
    question: "Satélite natural de la Tierra",
    answer: "Luna",
    difficulty: "facil",
    category: "astronomia",
  },
  {
    id: "l3",
    letter: "L",
    question: "Bebida blanca que dan las vacas",
    answer: "Leche",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "l7",
    letter: "L",
    question: "Estructura de caminos complicados diseñada para confundir",
    answer: "Laberinto",
    difficulty: "medio",
    category: "general",
  },
  {
    id: "dif-l1",
    letter: "L",
    question: "Coordenada geográfica que indica la distancia al ecuador",
    answer: "Latitud",
    difficulty: "dificil",
    category: "geografia",
  },
  {
    id: "m1",
    letter: "M",
    question: "Fruto del manzano",
    answer: "Manzana",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "m2",
    letter: "M",
    question: "Futbolista argentino apodado 'La Pulga'",
    answer: "Messi",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "m3",
    letter: "M",
    question: "Videojuego de construcción con bloques",
    answer: "Minecraft",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "dif-m1",
    letter: "M",
    question: "Orgánulo celular encargado de producir energía",
    answer: "Mitocondria",
    difficulty: "dificil",
    category: "biologia",
  },
  {
    id: "n1",
    letter: "N",
    question: "Masa de vapor de agua suspendida en la atmósfera",
    answer: "Nube",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "n2",
    letter: "N",
    question: "Órgano del olfato",
    answer: "Nariz",
    difficulty: "facil",
    category: "anatomia",
  },
  {
    id: "n3",
    letter: "N",
    question: "Plataforma de streaming de series y películas",
    answer: "Netflix",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "dif-n1",
    letter: "N",
    question: "Gas que compone la mayor parte del aire",
    answer: "Nitrógeno",
    difficulty: "dificil",
    category: "quimica",
  },
  {
    id: "o1",
    letter: "O",
    question: "Órgano de los sentidos para oír",
    answer: "Oído",
    difficulty: "facil",
    category: "anatomia",
  },
  {
    id: "o2",
    letter: "O",
    question: "Capital de Noruega",
    answer: "Oslo",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "o3",
    letter: "O",
    question: "Órganos de la vista",
    answer: "Ojos",
    difficulty: "facil",
    category: "anatomia",
  },
  {
    id: "dif-o1",
    letter: "O",
    question: "Trayectoria que sigue un cuerpo alrededor de otro por gravedad",
    answer: "Órbita",
    difficulty: "dificil",
    category: "astronomia",
  },
  {
    id: "p1",
    letter: "P",
    question: "Instrumento musical de teclas",
    answer: "Piano",
    difficulty: "medio",
    category: "musica",
  },
  {
    id: "p2",
    letter: "P",
    question: "Animal doméstico fiel al hombre",
    answer: "Perro",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "p3",
    letter: "P",
    question: "Comida italiana hecha con masa, salsa y queso",
    answer: "Pizza",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "dif-p1",
    letter: "P",
    question: "Supercontinente que existió hace cientos de millones de años",
    answer: "Pangea",
    difficulty: "dificil",
    category: "geologia",
  },
  {
    id: "q1",
    letter: "Q",
    question: "Ciencia que estudia las sustancias",
    answer: "Química",
    difficulty: "medio",
    category: "ciencia",
  },
  {
    id: "q2",
    letter: "Q",
    question: "Producto lácteo para untar",
    answer: "Queso",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "q3",
    letter: "Q",
    question: "Capital de Ecuador",
    answer: "Quito",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "dif-q1",
    letter: "Q",
    question: "Número mínimo de miembros necesarios para sesionar",
    answer: "Quórum",
    difficulty: "dificil",
    category: "derecho",
  },
  {
    id: "r1",
    letter: "R",
    question: "Animal roedor pequeño",
    answer: "Ratón",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "r2",
    letter: "R",
    question: "Corriente de agua natural",
    answer: "Río",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "r3",
    letter: "R",
    question: "Capital de Italia",
    answer: "Roma",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "dif-r1",
    letter: "R",
    question: "Energía que se propaga en forma de ondas o partículas",
    answer: "Radiación",
    difficulty: "dificil",
    category: "fisica",
  },
  {
    id: "s1",
    letter: "S",
    question: "Astro que da luz y calor",
    answer: "Sol",
    difficulty: "facil",
    category: "astronomia",
  },
  {
    id: "s2",
    letter: "S",
    question: "Reptil que reptan sin patas",
    answer: "Serpiente",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "s3",
    letter: "S",
    question: "Servicio de música en streaming",
    answer: "Spotify",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "dif-s1",
    letter: "S",
    question: "Conexión funcional entre neuronas para transmitir señales",
    answer: "Sinapsis",
    difficulty: "dificil",
    category: "biologia",
  },
  {
    id: "t1",
    letter: "T",
    question: "Medio de transporte sobre rieles",
    answer: "Tren",
    difficulty: "facil",
    category: "general",
  },
  {
    id: "t2",
    letter: "T",
    question: "Capital de Japón",
    answer: "Tokio",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "t3",
    letter: "T",
    question: "Animal felino con rayas",
    answer: "Tigre",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "dif-t1",
    letter: "T",
    question: "Instrumento que mide la temperatura",
    answer: "Termómetro",
    difficulty: "dificil",
    category: "instrumentos",
  },
  {
    id: "u1",
    letter: "U",
    question: "Vestimenta igual para todos en un grupo",
    answer: "Uniforme",
    difficulty: "facil",
    category: "vestimenta",
  },
  {
    id: "u2",
    letter: "U",
    question: "Fruta morada en racimos",
    answer: "Uva",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "u3",
    letter: "U",
    question: "Servicio de transporte por aplicación",
    answer: "Uber",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "dif-u1",
    letter: "U",
    question: "Tipo de radiación electromagnética más energética que la luz violeta",
    answer: "Ultravioleta",
    difficulty: "dificil",
    category: "fisica",
  },
  {
    id: "v1",
    letter: "V",
    question: "Animal que da leche",
    answer: "Vaca",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "v2",
    letter: "V",
    question: "Bebida alcohólica hecha de uvas",
    answer: "Vino",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "v3",
    letter: "V",
    question: "Deporte de pelota con red alta",
    answer: "Voleibol",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "dif-v1",
    letter: "V",
    question: "Sustancia que estimula defensas para prevenir enfermedades",
    answer: "Vacuna",
    difficulty: "dificil",
    category: "medicina",
  },
  {
    id: "w1",
    letter: "W",
    question: "Bebida alcohólica destilada de cereales",
    answer: "Whisky",
    difficulty: "medio",
    category: "bebidas",
  },
  {
    id: "w2",
    letter: "W",
    question: "Red informática mundial",
    answer: "Web",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "w3",
    letter: "W",
    question: "Aplicación de mensajería para teléfonos",
    answer: "WhatsApp",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "dif-w1",
    letter: "W",
    question: "Tecnología que permite conexión inalámbrica a internet",
    answer: "Wifi",
    difficulty: "dificil",
    category: "tecnologia",
  },
  {
    id: "x1",
    letter: "X",
    question: "Instrumento musical de percusión",
    answer: "Xilófono",
    difficulty: "medio",
    category: "musica",
  },
  {
    id: "x2",
    letter: "X",
    question: "Consola de videojuegos de Microsoft",
    answer: "Xbox",
    difficulty: "medio",
    category: "tecnologia",
  },
  {
    id: "dif-x1",
    letter: "X",
    question: "Elemento químico noble usado en lámparas y flashes",
    answer: "Xenón",
    difficulty: "dificil",
    category: "quimica",
  },
  {
    id: "y1",
    letter: "Y",
    question: "Plataforma de videos en línea más utilizada",
    answer: "YouTube",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "y2",
    letter: "Y",
    question: "Embarcación de recreo",
    answer: "Yate",
    difficulty: "medio",
    category: "nautica",
  },
  {
    id: "y3",
    letter: "Y",
    question: "Parte central del huevo",
    answer: "Yema",
    difficulty: "medio",
    category: "comida",
  },
  {
    id: "dif-y1",
    letter: "Y",
    question: "Elemento químico usado como antiséptico y en la tiroides",
    answer: "Yodo",
    difficulty: "dificil",
    category: "quimica",
  },
  {
    id: "z1",
    letter: "Z",
    question: "Plataforma de videollamadas muy usada en pandemia",
    answer: "Zoom",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "z2",
    letter: "Z",
    question: "Calzado que cubre el pie",
    answer: "Zapato",
    difficulty: "facil",
    category: "vestimenta",
  },
  {
    id: "z3",
    letter: "Z",
    question: "Lugar donde se exhiben animales",
    answer: "Zoológico",
    difficulty: "medio",
    category: "lugares",
  },
  {
    id: "dif-z1",
    letter: "Z",
    question: "Rama de la biología que estudia a los animales",
    answer: "Zoología",
    difficulty: "dificil",
    category: "biologia",
  },
]

function loadQuestionsFromStorage(): Question[] {
  if (typeof window !== "undefined") {
    const saved = localStorage.getItem("questionsArray")
    if (saved) {
      try {
        return JSON.parse(saved)
      } catch (error) {
        console.error("Error loading questions from storage:", error)
      }
    }
  }
  return questionsDatabase
}

const currentQuestions = loadQuestionsFromStorage()

export const questionsData: Record<string, Question[]> = {}

currentQuestions.forEach((question) => {
  if (!questionsData[question.letter]) {
    questionsData[question.letter] = []
  }
  questionsData[question.letter].push(question)
})

export function getRandomQuestion(letter: string, difficulty: "facil" | "medio" | "dificil"): Question | null {
  const updatedQuestions = loadQuestionsFromStorage()
  const updatedQuestionsData: Record<string, Question[]> = {}

  updatedQuestions.forEach((question) => {
    if (!updatedQuestionsData[question.letter]) {
      updatedQuestionsData[question.letter] = []
    }
    updatedQuestionsData[question.letter].push(question)
  })

  const letterQuestions = updatedQuestionsData[letter] || []
  const filteredQuestions = letterQuestions.filter((q) => q.difficulty === difficulty)

  if (filteredQuestions.length === 0) {
    // Si no hay preguntas de esa dificultad, usar cualquier dificultad
    const allQuestions = letterQuestions
    if (allQuestions.length === 0) return null
    return allQuestions[Math.floor(Math.random() * allQuestions.length)]
  }

  return filteredQuestions[Math.floor(Math.random() * filteredQuestions.length)]
}

export function getAllLetters(): string[] {
  return "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("")
}
