export interface Question {
  id: string
  letter: string
  question: string
  answer: string
  difficulty: "facil" | "medio" | "dificil"
  category?: string
}

export const questionsDatabase: Question[] = [
  {
    id: "a1",
    letter: "A",
    question: "Conjunto de partículas minerales en la playa",
    answer: "Arena",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "a2",
    letter: "A",
    question: "Animal que vuela y tiene plumas",
    answer: "Ave",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "a3",
    letter: "A",
    question: "Líquido transparente e incoloro esencial para la vida",
    answer: "Agua",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "a4",
    letter: "A",
    question: "Instrumento musical de cuerda pulsada",
    answer: "Arpa",
    difficulty: "medio",
    category: "musica",
  },
  {
    id: "a5",
    letter: "A",
    question: "Capital de Grecia",
    answer: "Atenas",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "a6",
    letter: "A",
    question: "Ciencia que estudia los astros",
    answer: "Astronomía",
    difficulty: "medio",
    category: "ciencia",
  },
  {
    id: "a7",
    letter: "A",
    question: "Deporte acuático que se practica en piscina",
    answer: "Aquaeróbicos",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "a8",
    letter: "A",
    question: "Plataforma de comercio electrónico más grande",
    answer: "Amazon",
    difficulty: "medio",
    category: "tecnologia",
  },
  {
    id: "a9",
    letter: "A",
    question: "Cantante británica de 'Hello' y 'Someone Like You'",
    answer: "Adele",
    difficulty: "medio",
    category: "espectaculos",
  },
  {
    id: "a10",
    letter: "A",
    question: "País europeo famoso por Oktoberfest",
    answer: "Alemania",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "a11",
    letter: "A",
    question: "Continente helado",
    answer: "Antártida",
    difficulty: "facil",
    category: "geografia",
  },
  {
    id: "a12",
    letter: "A",
    question: "Empresa tecnológica creadora del iPhone",
    answer: "Apple",
    difficulty: "medio",
    category: "tecnologia",
  },
  {
    id: "a13",
    letter: "A",
    question: "Sistema operativo de Google para móviles",
    answer: "Android",
    difficulty: "medio",
    category: "tecnologia",
  },
  {
    id: "a14",
    letter: "A",
    question: "Juego de estrategia con piezas en un tablero de 64 casillas",
    answer: "Ajedrez",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "a15",
    letter: "A",
    question: "Comida asiática con granos blancos",
    answer: "Arroz",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "a16",
    letter: "A",
    question: "Medio de transporte aéreo",
    answer: "Avión",
    difficulty: "facil",
    category: "transporte",
  },
  {
    id: "b1",
    letter: "B",
    question: "Sitio poblado de árboles y matas",
    answer: "Bosque",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "b2",
    letter: "B",
    question: "Deporte que se juega con una pelota y dos aros elevados",
    answer: "Baloncesto",
    difficulty: "facil",
    category: "deportes",
  },
  {
    id: "b3",
    letter: "B",
    question: "Embarcación para navegar",
    answer: "Barco",
    difficulty: "facil",
    category: "transporte",
  },
  {
    id: "b4",
    letter: "B",
    question: "Instrumento musical de percusión",
    answer: "Batería",
    difficulty: "medio",
    category: "musica",
  },
  {
    id: "b5",
    letter: "B",
    question: "Capital de Alemania",
    answer: "Berlín",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "b6",
    letter: "B",
    question: "Ciencia que estudia los seres vivos",
    answer: "Biología",
    difficulty: "medio",
    category: "ciencia",
  },
  {
    id: "b7",
    letter: "B",
    question: "Película de superhéroes protagonizada por Christian Bale",
    answer: "Batman",
    difficulty: "medio",
    category: "espectaculos",
  },
  {
    id: "b8",
    letter: "B",
    question: "Deporte de combate que se practica en un ring",
    answer: "Boxeo",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "b9",
    letter: "B",
    question: "Capital de Hungría",
    answer: "Budapest",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "b10",
    letter: "B",
    question: "Animal nocturno que ulula",
    answer: "Búho",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "c1",
    letter: "C",
    question: "Bebida fermentada de cebada",
    answer: "Cerveza",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "c2",
    letter: "C",
    question: "Bebida caliente hecha con granos tostados",
    answer: "Café",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "c3",
    letter: "C",
    question: "Vehículo de cuatro ruedas",
    answer: "Coche",
    difficulty: "facil",
    category: "transporte",
  },
  {
    id: "c4",
    letter: "C",
    question: "Lugar donde vive el rey",
    answer: "Castillo",
    difficulty: "facil",
    category: "historia",
  },
  {
    id: "c5",
    letter: "C",
    question: "Capital de Dinamarca",
    answer: "Copenhague",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "c6",
    letter: "C",
    question: "Técnica de salto y entrada al agua en natación",
    answer: "Clavado",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "c7",
    letter: "C",
    question: "Sabor dulce que se mastica",
    answer: "Chicle",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "c8",
    letter: "C",
    question: "Animal que relincha",
    answer: "Caballo",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "c9",
    letter: "C",
    question: "Órgano que bombea sangre",
    answer: "Corazón",
    difficulty: "facil",
    category: "anatomia",
  },
  {
    id: "c10",
    letter: "C",
    question: "Actor estadounidense de Misión Imposible",
    answer: "Cruise",
    difficulty: "medio",
    category: "espectaculos",
  },
  {
    id: "c11",
    letter: "C",
    question: "Animal que salta mucho",
    answer: "Canguro",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "c12",
    letter: "C",
    question: "Animal rayado parecido al caballo",
    answer: "Cebra",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "d1",
    letter: "D",
    question: "Actor estadounidense protagonista de Titanic",
    answer: "DiCaprio",
    difficulty: "dificil",
    category: "espectaculos",
  },
  {
    id: "d2",
    letter: "D",
    question: "Territorio arenoso o pedregoso con escasa vegetación",
    answer: "Desierto",
    difficulty: "facil",
    category: "geografia",
  },
  {
    id: "d3",
    letter: "D",
    question: "Extremidades de la mano",
    answer: "Dedos",
    difficulty: "facil",
    category: "anatomia",
  },
  {
    id: "d4",
    letter: "D",
    question: "Moneda de Estados Unidos",
    answer: "Dólar",
    difficulty: "facil",
    category: "economia",
  },
  {
    id: "d5",
    letter: "D",
    question: "Forma de gobierno donde el pueblo elige",
    answer: "Democracia",
    difficulty: "medio",
    category: "politica",
  },
  {
    id: "e1",
    letter: "E",
    question: "Ocultación de un astro por otro",
    answer: "Eclipse",
    difficulty: "facil",
    category: "astronomia",
  },
  {
    id: "e2",
    letter: "E",
    question: "Animal paquidermo con trompa",
    answer: "Elefante",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "e3",
    letter: "E",
    question: "Lugar donde se enseña",
    answer: "Escuela",
    difficulty: "facil",
    category: "educacion",
  },
  {
    id: "e4",
    letter: "E",
    question: "Deporte olímpico de combate con espadas",
    answer: "Esgrima",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "e5",
    letter: "E",
    question: "Capital de Escocia",
    answer: "Edimburgo",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "e6",
    letter: "E",
    question: "Capital de Suecia",
    answer: "Estocolmo",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "f1",
    letter: "F",
    question: "Competición de automovilismo de monoplazas más popular",
    answer: "Fórmula1",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "f2",
    letter: "F",
    question: "Historia breve con enseñanza moral",
    answer: "Fábula",
    difficulty: "facil",
    category: "literatura",
  },
  {
    id: "f3",
    letter: "F",
    question: "Deporte que se juega con los pies",
    answer: "Fútbol",
    difficulty: "facil",
    category: "deportes",
  },
  {
    id: "f4",
    letter: "F",
    question: "Red social más grande del mundo",
    answer: "Facebook",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "f5",
    letter: "F",
    question: "Instrumento musical de viento",
    answer: "Flauta",
    difficulty: "medio",
    category: "musica",
  },
  {
    id: "f6",
    letter: "F",
    question: "País europeo famoso por la Torre Eiffel",
    answer: "Francia",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "f7",
    letter: "F",
    question: "Ciencia que estudia las fuerzas",
    answer: "Física",
    difficulty: "medio",
    category: "ciencia",
  },
  {
    id: "f8",
    letter: "F",
    question: "Tenista suizo ganador de 20 Grand Slams",
    answer: "Federer",
    difficulty: "dificil",
    category: "deportes",
  },
  {
    id: "g1",
    letter: "G",
    question: "Animal doméstico que maúlla",
    answer: "Gato",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "g2",
    letter: "G",
    question: "Ser muy grande o persona de gran estatura",
    answer: "Gigante",
    difficulty: "facil",
    category: "general",
  },
  {
    id: "g3",
    letter: "G",
    question: "Deporte que se juega con palos y pelota pequeña",
    answer: "Golf",
    difficulty: "facil",
    category: "deportes",
  },
  {
    id: "g4",
    letter: "G",
    question: "Lugar donde se guardan los coches",
    answer: "Garaje",
    difficulty: "facil",
    category: "hogar",
  },
  {
    id: "g5",
    letter: "G",
    question: "Instrumento musical de cuerda con caja de resonancia",
    answer: "Guitarra",
    difficulty: "medio",
    category: "musica",
  },
  {
    id: "g6",
    letter: "G",
    question: "Buscador de internet más utilizado",
    answer: "Google",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "g7",
    letter: "G",
    question: "Cantante estadounidense de 'Bad Romance'",
    answer: "Gaga",
    difficulty: "medio",
    category: "espectaculos",
  },
  {
    id: "g8",
    letter: "G",
    question: "Helado italiano cremoso",
    answer: "Gelato",
    difficulty: "medio",
    category: "comida",
  },
  {
    id: "h1",
    letter: "H",
    question: "Postre frío hecho con leche y azúcar",
    answer: "Helado",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "h2",
    letter: "H",
    question: "Entrar en reposo durante el invierno",
    answer: "Hibernar",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "h3",
    letter: "H",
    question: "Lugar donde vive una familia",
    answer: "Hogar",
    difficulty: "facil",
    category: "general",
  },
  {
    id: "h4",
    letter: "H",
    question: "Deporte que se juega sobre hielo",
    answer: "Hockey",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "h5",
    letter: "H",
    question: "Ciencia que estudia el pasado",
    answer: "Historia",
    difficulty: "medio",
    category: "ciencia",
  },
  {
    id: "h6",
    letter: "H",
    question: "Comida rápida con carne entre dos panes",
    answer: "Hamburguesa",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "i1",
    letter: "I",
    question: "Aplicación móvil para compartir fotos",
    answer: "Instagram",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "i2",
    letter: "I",
    question: "Que representa algo de forma típica",
    answer: "Icónico",
    difficulty: "facil",
    category: "general",
  },
  {
    id: "i3",
    letter: "I",
    question: "Órgano que procesa los alimentos",
    answer: "Intestino",
    difficulty: "facil",
    category: "anatomia",
  },
  {
    id: "i4",
    letter: "I",
    question: "Lugar donde se reza",
    answer: "Iglesia",
    difficulty: "facil",
    category: "religion",
  },
  {
    id: "i5",
    letter: "I",
    question: "Lengua oficial de Italia",
    answer: "Italiano",
    difficulty: "medio",
    category: "idiomas",
  },
  {
    id: "i6",
    letter: "I",
    question: "Estación del año más fría",
    answer: "Invierno",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "j1",
    letter: "J",
    question: "Caja con barrotes para encerrar animales",
    answer: "Jaula",
    difficulty: "facil",
    category: "general",
  },
  {
    id: "j2",
    letter: "J",
    question: "Lugar donde se cultivan plantas",
    answer: "Jardín",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "j3",
    letter: "J",
    question: "Profesión que administra justicia",
    answer: "Juez",
    difficulty: "medio",
    category: "profesiones",
  },
  {
    id: "j4",
    letter: "J",
    question: "Cantante estadounidense 'King of Pop'",
    answer: "Jackson",
    difficulty: "medio",
    category: "espectaculos",
  },
  {
    id: "j5",
    letter: "J",
    question: "Basquetbolista considerado el mejor de todos los tiempos",
    answer: "Jordan",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "k1",
    letter: "K",
    question: "Túnica tradicional japonesa",
    answer: "Kimono",
    difficulty: "facil",
    category: "cultura",
  },
  {
    id: "k2",
    letter: "K",
    question: "Unidad de peso de mil gramos",
    answer: "Kilogramo",
    difficulty: "facil",
    category: "medidas",
  },
  {
    id: "k3",
    letter: "K",
    question: "Arte marcial japonés de golpes con manos y pies",
    answer: "Karate",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "k4",
    letter: "K",
    question: "Aderezo de tomate dulce y ácido",
    answer: "Ketchup",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "l1",
    letter: "L",
    question: "Red social para profesionales",
    answer: "LinkedIn",
    difficulty: "medio",
    category: "tecnologia",
  },
  {
    id: "l2",
    letter: "L",
    question: "Parte de la garganta que contiene las cuerdas vocales",
    answer: "Laringe",
    difficulty: "dificil",
    category: "anatomia",
  },
  {
    id: "l3",
    letter: "L",
    question: "Animal que ruge en la selva",
    answer: "León",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "l4",
    letter: "L",
    question: "Satélite natural de la Tierra",
    answer: "Luna",
    difficulty: "facil",
    category: "astronomia",
  },
  {
    id: "l5",
    letter: "L",
    question: "Capital de Perú",
    answer: "Lima",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "l6",
    letter: "L",
    question: "Bebida blanca que dan las vacas",
    answer: "Leche",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "l7",
    letter: "L",
    question: "Estructura de caminos complicados diseñada para confundir",
    answer: "Laberinto",
    difficulty: "medio",
    category: "general",
  },
  {
    id: "l8",
    letter: "L",
    question: "Deporte de combate libre",
    answer: "Lucha",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "m1",
    letter: "M",
    question: "Fruto del manzano",
    answer: "Manzana",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "m2",
    letter: "M",
    question: "Futbolista argentino apodado 'La Pulga'",
    answer: "Messi",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "m3",
    letter: "M",
    question: "Fragmento de cuerpo celeste que cae a la Tierra",
    answer: "Meteorito",
    difficulty: "dificil",
    category: "ciencia",
  },
  {
    id: "m4",
    letter: "M",
    question: "Videojuego de construcción con bloques",
    answer: "Minecraft",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "m5",
    letter: "M",
    question: "Insecto lepidóptero de alas grandes y coloridas",
    answer: "Mariposa",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "m6",
    letter: "M",
    question: "Capital de España",
    answer: "Madrid",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "m7",
    letter: "M",
    question: "Empresa tecnológica creadora de Windows",
    answer: "Microsoft",
    difficulty: "medio",
    category: "tecnologia",
  },
  {
    id: "m8",
    letter: "M",
    question: "Cantante estadounidense 'Queen of Pop'",
    answer: "Madonna",
    difficulty: "medio",
    category: "espectaculos",
  },
  {
    id: "m9",
    letter: "M",
    question: "Deporte de combate mixto",
    answer: "MMA",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "m10",
    letter: "M",
    question: "Capital de Uruguay",
    answer: "Montevideo",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "n1",
    letter: "N",
    question: "Capital de Kenia",
    answer: "Nairobi",
    difficulty: "dificil",
    category: "geografia",
  },
  {
    id: "n2",
    letter: "N",
    question: "Masa de vapor de agua suspendida en la atmósfera",
    answer: "Nube",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "n3",
    letter: "N",
    question: "Órgano del olfato",
    answer: "Nariz",
    difficulty: "facil",
    category: "anatomia",
  },
  {
    id: "n4",
    letter: "N",
    question: "Plataforma de streaming de series y películas",
    answer: "Netflix",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "n5",
    letter: "N",
    question: "Tenista español ganador de 22 Grand Slams",
    answer: "Nadal",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "n6",
    letter: "N",
    question: "Deporte acuático de resistencia",
    answer: "Natación",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "o1",
    letter: "O",
    question: "Obra teatral musical con canto y orquesta",
    answer: "Ópera",
    difficulty: "medio",
    category: "cultura",
  },
  {
    id: "o2",
    letter: "O",
    question: "Órgano de los sentidos para oír",
    answer: "Oído",
    difficulty: "facil",
    category: "anatomia",
  },
  {
    id: "o3",
    letter: "O",
    question: "Capital de Noruega",
    answer: "Oslo",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "o4",
    letter: "O",
    question: "Movimientos que se propagan en un medio",
    answer: "Ondas",
    difficulty: "facil",
    category: "fisica",
  },
  {
    id: "o5",
    letter: "O",
    question: "Órganos de la vista",
    answer: "Ojos",
    difficulty: "facil",
    category: "anatomia",
  },
  {
    id: "o6",
    letter: "O",
    question: "Capital de Canadá",
    answer: "Ottawa",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "o7",
    letter: "O",
    question: "Metal precioso amarillo",
    answer: "Oro",
    difficulty: "facil",
    category: "minerales",
  },
  {
    id: "p1",
    letter: "P",
    question: "Instrumento musical de teclas",
    answer: "Piano",
    difficulty: "medio",
    category: "musica",
  },
  {
    id: "p2",
    letter: "P",
    question: "Recurso natural fósil usado como combustible",
    answer: "Petróleo",
    difficulty: "medio",
    category: "ciencia",
  },
  {
    id: "p3",
    letter: "P",
    question: "Animal doméstico fiel al hombre",
    answer: "Perro",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "p4",
    letter: "P",
    question: "Servicio de música en streaming de Spotify",
    answer: "Premium",
    difficulty: "medio",
    category: "tecnologia",
  },
  {
    id: "p5",
    letter: "P",
    question: "Situación embarazosa o vergonzosa",
    answer: "Papelón",
    difficulty: "facil",
    category: "general",
  },
  {
    id: "p6",
    letter: "P",
    question: "Bastones de papa fritos, clásicos de la comida rápida",
    answer: "Papas",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "p7",
    letter: "P",
    question: "Comida italiana hecha con masa, salsa y queso",
    answer: "Pizza",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "p8",
    letter: "P",
    question: "Fruta amarilla alargada",
    answer: "Plátano",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "p9",
    letter: "P",
    question: "Persona que viaja a un lugar sagrado por motivos religiosos",
    answer: "Peregrino",
    difficulty: "medio",
    category: "cultura",
  },
  {
    id: "p10",
    letter: "P",
    question: "Giro elegante realizado al bailar o patinar",
    answer: "Pirueta",
    difficulty: "facil",
    category: "danza",
  },
  {
    id: "p11",
    letter: "P",
    question: "Ave que no vuela y vive en el hielo",
    answer: "Pingüino",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "p12",
    letter: "P",
    question: "Fruta redonda y dulce",
    answer: "Pera",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "p13",
    letter: "P",
    question: "Capital de Francia",
    answer: "París",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "p14",
    letter: "P",
    question: "Antiguo material para escribir usado en Egipto",
    answer: "Papiro",
    difficulty: "dificil",
    category: "historia",
  },
  {
    id: "p15",
    letter: "P",
    question: "Cantante estadounidense de 'Roar'",
    answer: "Perry",
    difficulty: "medio",
    category: "espectaculos",
  },
  {
    id: "p16",
    letter: "P",
    question: "Deporte de raqueta individual",
    answer: "Ping-pong",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "p17",
    letter: "P",
    question: "Instrumento para protegerse de la lluvia",
    answer: "Paraguas",
    difficulty: "facil",
    category: "objetos",
  },
  {
    id: "q1",
    letter: "Q",
    question: "Ciencia que estudia las sustancias",
    answer: "Química",
    difficulty: "medio",
    category: "ciencia",
  },
  {
    id: "q2",
    letter: "Q",
    question: "Construcción pequeña que se instala en la vía pública",
    answer: "Quiosco",
    difficulty: "facil",
    category: "arquitectura",
  },
  {
    id: "q3",
    letter: "Q",
    question: "Producto lácteo para untar",
    answer: "Queso",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "q4",
    letter: "Q",
    question: "Palabra real que empieza con Q",
    answer: "Qpalabra",
    difficulty: "medio",
    category: "general",
  },
  {
    id: "q5",
    letter: "Q",
    question: "Capital de Ecuador",
    answer: "Quito",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "q6",
    letter: "Q",
    question: "Comida mexicana con tortilla doblada",
    answer: "Quesadilla",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "r1",
    letter: "R",
    question: "Saga de películas sobre autos y velocidad",
    answer: "Rápidos",
    difficulty: "medio",
    category: "espectaculos",
  },
  {
    id: "r2",
    letter: "R",
    question: "Actor británico que interpretó a Harry Potter",
    answer: "Radcliffe",
    difficulty: "medio",
    category: "espectaculos",
  },
  {
    id: "r3",
    letter: "R",
    question: "Capital de Islandia",
    answer: "Reikiavik",
    difficulty: "dificil",
    category: "geografia",
  },
  {
    id: "r4",
    letter: "R",
    question: "Actor estadounidense de Matrix",
    answer: "Reeves",
    difficulty: "dificil",
    category: "espectaculos",
  },
  {
    id: "r5",
    letter: "R",
    question: "Posibilidad de sufrir daño",
    answer: "Riesgo",
    difficulty: "facil",
    category: "general",
  },
  {
    id: "r6",
    letter: "R",
    question: "Animal roedor pequeño",
    answer: "Ratón",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "r7",
    letter: "R",
    question: "Corriente de agua natural",
    answer: "Río",
    difficulty: "facil",
    category: "naturaleza",
  },
  {
    id: "r8",
    letter: "R",
    question: "Capital de Italia",
    answer: "Roma",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "r9",
    letter: "R",
    question: "Red social y agregador de contenidos",
    answer: "Reddit",
    difficulty: "medio",
    category: "tecnologia",
  },
  {
    id: "r10",
    letter: "R",
    question: "Cantante barbadense de 'Umbrella'",
    answer: "Rihanna",
    difficulty: "medio",
    category: "espectaculos",
  },
  {
    id: "r11",
    letter: "R",
    question: "Deporte de equipo de contacto con pelota ovalada y scrum",
    answer: "Rugby",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "s1",
    letter: "S",
    question: "Director de cine estadounidense de Tiburón",
    answer: "Spielberg",
    difficulty: "dificil",
    category: "espectaculos",
  },
  {
    id: "s2",
    letter: "S",
    question: "Formato audiovisual por capítulos",
    answer: "Series",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "s3",
    letter: "S",
    question: "Cantante colombiana de 'Hips Don't Lie'",
    answer: "Shakira",
    difficulty: "medio",
    category: "espectaculos",
  },
  {
    id: "s4",
    letter: "S",
    question: "Relativo a lo sagrado",
    answer: "Sacro",
    difficulty: "facil",
    category: "religion",
  },
  {
    id: "s5",
    letter: "S",
    question: "Astro que da luz y calor",
    answer: "Sol",
    difficulty: "facil",
    category: "astronomia",
  },
  {
    id: "s6",
    letter: "S",
    question: "Reptil que reptan sin patas",
    answer: "Serpiente",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "s7",
    letter: "S",
    question: "Comida italiana larga y delgada",
    answer: "Spaghetti",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "s8",
    letter: "S",
    question: "Servicio de música en streaming",
    answer: "Spotify",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "s9",
    letter: "S",
    question: "Cantante estadounidense de 'Shake It Off'",
    answer: "Swift",
    difficulty: "medio",
    category: "espectaculos",
  },
  {
    id: "s10",
    letter: "S",
    question: "Deporte acuático con tabla",
    answer: "Surf",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "t1",
    letter: "T",
    question: "Medio de transporte sobre rieles",
    answer: "Tren",
    difficulty: "facil",
    category: "general",
  },
  {
    id: "t2",
    letter: "T",
    question: "Capital de Japón",
    answer: "Tokio",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "t3",
    letter: "T",
    question: "Parte que dirige la embarcación",
    answer: "Timón",
    difficulty: "facil",
    category: "nautica",
  },
  {
    id: "t4",
    letter: "T",
    question: "Animal felino con rayas",
    answer: "Tigre",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "t5",
    letter: "T",
    question: "Aparato para comunicarse a distancia",
    answer: "Teléfono",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "t6",
    letter: "T",
    question: "Membrana del oído que vibra con el sonido",
    answer: "Tímpano",
    difficulty: "medio",
    category: "ciencia",
  },
  {
    id: "t7",
    letter: "T",
    question: "Baile típico de Argentina",
    answer: "Tango",
    difficulty: "medio",
    category: "danza",
  },
  {
    id: "t8",
    letter: "T",
    question: "Bebida mexicana hecha de agave",
    answer: "Tequila",
    difficulty: "medio",
    category: "comida",
  },
  {
    id: "t9",
    letter: "T",
    question: "Red social de mensajes cortos",
    answer: "Twitter",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "t10",
    letter: "T",
    question: "Deporte de raqueta individual",
    answer: "Tenis",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "u1",
    letter: "U",
    question: "Vestimenta igual para todos en un grupo",
    answer: "Uniforme",
    difficulty: "facil",
    category: "vestimenta",
  },
  {
    id: "u2",
    letter: "U",
    question: "Fruta morada en racimos",
    answer: "Uva",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "u3",
    letter: "U",
    question: "Servicio de transporte por aplicación",
    answer: "Uber",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "v1",
    letter: "V",
    question: "Grabación visual de una escena o evento",
    answer: "Vídeo",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "v2",
    letter: "V",
    question: "Animal que da leche",
    answer: "Vaca",
    difficulty: "facil",
    category: "animales",
  },
  {
    id: "v3",
    letter: "V",
    question: "Capital de Austria",
    answer: "Viena",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "v4",
    letter: "V",
    question: "Bebida alcohólica hecha de uvas",
    answer: "Vino",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "v5",
    letter: "V",
    question: "Deporte de pelota con red alta",
    answer: "Voleibol",
    difficulty: "medio",
    category: "deportes",
  },
  {
    id: "w1",
    letter: "W",
    question: "Actriz estadounidense protagonista de Titanic",
    answer: "Winslet",
    difficulty: "dificil",
    category: "espectaculos",
  },
  {
    id: "w2",
    letter: "W",
    question: "Bebida alcohólica destilada de cereales",
    answer: "Whisky",
    difficulty: "medio",
    category: "bebidas",
  },
  {
    id: "w3",
    letter: "W",
    question: "Red informática mundial",
    answer: "Web",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "w4",
    letter: "W",
    question: "Pastel enrejado típico de Bélgica",
    answer: "Wafle",
    difficulty: "facil",
    category: "comida",
  },
  {
    id: "w5",
    letter: "W",
    question: "Capital de Estados Unidos",
    answer: "Washington",
    difficulty: "medio",
    category: "geografia",
  },
  {
    id: "w6",
    letter: "W",
    question: "Aplicación de mensajería para teléfonos",
    answer: "WhatsApp",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "x1",
    letter: "X",
    question: "Forma de grabado sobre madera",
    answer: "Xilografía",
    difficulty: "facil",
    category: "arte",
  },
  {
    id: "x2",
    letter: "X",
    question: "Instrumento musical de percusión",
    answer: "Xilófono",
    difficulty: "medio",
    category: "musica",
  },
  {
    id: "x3",
    letter: "X",
    question: "Consola de videojuegos de Microsoft",
    answer: "Xbox",
    difficulty: "medio",
    category: "tecnologia",
  },
  {
    id: "y1",
    letter: "Y",
    question: "Plataforma de videos en línea más utilizada",
    answer: "YouTube",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "y2",
    letter: "Y",
    question: "Persona que vende o prepara hierbas medicinales",
    answer: "Yerbatero",
    difficulty: "facil",
    category: "profesiones",
  },
  {
    id: "y3",
    letter: "Y",
    question: "Embarcación de recreo",
    answer: "Yate",
    difficulty: "medio",
    category: "nautica",
  },
  {
    id: "y4",
    letter: "Y",
    question: "Parte central del huevo",
    answer: "Yema",
    difficulty: "medio",
    category: "comida",
  },
  {
    id: "z1",
    letter: "Z",
    question: "Plataforma de videollamadas muy usada en pandemia",
    answer: "Zoom",
    difficulty: "facil",
    category: "tecnologia",
  },
  {
    id: "z2",
    letter: "Z",
    question: "Dirigible rígido de gran tamaño",
    answer: "Zeppelin",
    difficulty: "facil",
    category: "transporte",
  },
  {
    id: "z3",
    letter: "Z",
    question: "Calzado que cubre el pie",
    answer: "Zapato",
    difficulty: "facil",
    category: "vestimenta",
  },
  {
    id: "z4",
    letter: "Z",
    question: "Lugar donde se exhiben animales",
    answer: "Zoológico",
    difficulty: "medio",
    category: "lugares",
  },
]

export const questionsData = questionsDatabase

export const getCustomQuestions = (): Question[] => {
  if (typeof window === "undefined") return []

  try {
    const saved = localStorage.getItem("pasapalabra-custom-questions")
    return saved ? JSON.parse(saved) : []
  } catch (error) {
    console.error("Error loading custom questions:", error)
    return []
  }
}

export const getQuestionsByLetter = (letter: string, difficulty?: string): Question[] => {
  const defaultQuestions = questionsDatabase
    .filter((q) => q.letter === letter.toUpperCase() && (difficulty ? q.difficulty === difficulty : true))
    .map((q) => {
      // Reemplazar la pregunta problemática
      if (q.id === "l7" && q.answer === "Lpalabra") {
        return {
          ...q,
          question: "Estructura de caminos complicados diseñada para confundir",
          answer: "Laberinto",
          difficulty: "medio",
          category: "general",
        }
      }
      return q
    })

  const customQuestions = getCustomQuestions().filter(
    (q) => q.letter === letter.toUpperCase() && (difficulty ? q.difficulty === difficulty : true),
  )

  return [...defaultQuestions, ...customQuestions]
}

export const getRandomQuestion = (letter: string, difficulty?: string): Question | null => {
  const questions = getQuestionsByLetter(letter, difficulty)
  if (questions.length === 0) return null
  return questions[Math.floor(Math.random() * questions.length)]
}

export const getAllLetters = (): string[] => {
  return "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("")
}
