-- Eliminar tabla existente y recrear con estructura correcta
DROP TABLE IF EXISTS questions;

-- Crear tabla con estructura simple y sin constraints problemáticas
CREATE TABLE questions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  question_id TEXT NOT NULL,
  letter TEXT NOT NULL,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  difficulty TEXT NOT NULL,
  category TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Crear índices para mejorar rendimiento
CREATE INDEX idx_questions_letter ON questions(letter);
CREATE INDEX idx_questions_difficulty ON questions(difficulty);
CREATE INDEX idx_questions_question_id ON questions(question_id);

-- Insertar todas las preguntas correctas
INSERT INTO questions (question_id, letter, question, answer, difficulty, category) VALUES
('a1', 'A', 'Conjunto de partículas minerales en la playa', 'Arena', 'facil', 'naturaleza'),
('a2', 'A', 'Animal que vuela y tiene plumas', 'Ave', 'facil', 'animales'),
('a3', 'A', 'Líquido transparente e incoloro esencial para la vida', 'Agua', 'facil', 'naturaleza'),
('a4', 'A', 'Instrumento musical de cuerda pulsada', 'Arpa', 'medio', 'musica'),
('a5', 'A', 'Capital de Grecia', 'Atenas', 'medio', 'geografia'),
('dif-a1', 'A', 'Sustancia que combate infecciones bacterianas', 'Antibiótico', 'dificil', 'medicina'),
('b1', 'B', 'Sitio poblado de árboles y matas', 'Bosque', 'facil', 'naturaleza'),
('b2', 'B', 'Deporte que se juega con una pelota y dos aros elevados', 'Baloncesto', 'facil', 'deportes'),
('b3', 'B', 'Embarcación para navegar', 'Barco', 'facil', 'transporte'),
('dif-b1', 'B', 'Escritor argentino autor de ''El Aleph'' y ''Ficciones''', 'Borges', 'dificil', 'literatura'),
('c1', 'C', 'Bebida fermentada de cebada', 'Cerveza', 'facil', 'comida'),
('c2', 'C', 'Bebida caliente hecha con granos tostados', 'Café', 'facil', 'comida'),
('c3', 'C', 'Vehículo de cuatro ruedas', 'Coche', 'facil', 'transporte'),
('dif-c1', 'C', 'Tejido flexible que recubre articulaciones y nariz', 'Cartílago', 'dificil', 'anatomia'),
('d1', 'D', 'Actor estadounidense protagonista de Titanic', 'DiCaprio', 'dificil', 'espectaculos'),
('d2', 'D', 'Territorio arenoso o pedregoso con escasa vegetación', 'Desierto', 'facil', 'geografia'),
('d3', 'D', 'Forma de gobierno donde el pueblo elige', 'Democracia', 'medio', 'politica'),
('dif-d1', 'D', 'Gas formado por carbono y oxígeno presente en respiración y combustión', 'Dióxido de carbono', 'dificil', 'quimica'),
('e1', 'E', 'Ocultación de un astro por otro', 'Eclipse', 'facil', 'astronomia'),
('e2', 'E', 'Animal paquidermo con trompa', 'Elefante', 'facil', 'animales'),
('e3', 'E', 'Lugar donde se enseña', 'Escuela', 'facil', 'educacion'),
('dif-e1', 'E', 'Conjunto de seres vivos y su entorno que interactúan', 'Ecosistema', 'dificil', 'ciencia'),
('f1', 'F', 'Deporte que se juega con los pies', 'Fútbol', 'facil', 'deportes'),
('f2', 'F', 'Historia breve con enseñanza moral', 'Fábula', 'facil', 'literatura'),
('f3', 'F', 'Red social más grande del mundo', 'Facebook', 'facil', 'tecnologia'),
('dif-f1', 'F', 'Proceso por el cual las plantas convierten luz en energía', 'Fotosíntesis', 'dificil', 'biologia'),
('g1', 'G', 'Animal doméstico que maúlla', 'Gato', 'facil', 'animales'),
('g2', 'G', 'Deporte que se juega con palos y pelota pequeña', 'Golf', 'facil', 'deportes'),
('g3', 'G', 'Buscador de internet más utilizado', 'Google', 'facil', 'tecnologia'),
('dif-g1', 'G', 'Masa de hielo en movimiento formada por acumulación de nieve', 'Glaciar', 'dificil', 'geografia'),
('h1', 'H', 'Postre frío hecho con leche y azúcar', 'Helado', 'facil', 'comida'),
('h2', 'H', 'Lugar donde vive una familia', 'Hogar', 'facil', 'general'),
('h3', 'H', 'Deporte que se juega sobre hielo', 'Hockey', 'medio', 'deportes'),
('dif-h1', 'H', 'Proteína de la sangre que transporta oxígeno', 'Hemoglobina', 'dificil', 'biologia'),
('i1', 'I', 'Aplicación móvil para compartir fotos', 'Instagram', 'facil', 'tecnologia'),
('i2', 'I', 'Lugar donde se reza', 'Iglesia', 'facil', 'religion'),
('i3', 'I', 'Estación del año más fría', 'Invierno', 'facil', 'naturaleza'),
('dif-i1', 'I', 'Aumento generalizado y sostenido de los precios', 'Inflación', 'dificil', 'economia'),
('j1', 'J', 'Lugar donde se cultivan plantas', 'Jardín', 'facil', 'naturaleza'),
('j2', 'J', 'Profesión que administra justicia', 'Juez', 'medio', 'profesiones'),
('j3', 'J', 'Cantante estadounidense ''King of Pop''', 'Jackson', 'medio', 'espectaculos'),
('dif-j1', 'J', 'Planeta más grande del sistema solar', 'Júpiter', 'dificil', 'astronomia'),
('k1', 'K', 'Unidad de peso de mil gramos', 'Kilogramo', 'facil', 'medidas'),
('k2', 'K', 'Arte marcial japonés de golpes con manos y pies', 'Karate', 'medio', 'deportes'),
('k3', 'K', 'Aderezo de tomate dulce y ácido', 'Ketchup', 'facil', 'comida'),
('dif-k1', 'K', 'Unidad de longitud equivalente a mil metros', 'Kilómetro', 'dificil', 'medidas'),
('l1', 'L', 'Animal que ruge en la selva', 'León', 'facil', 'animales'),
('l2', 'L', 'Satélite natural de la Tierra', 'Luna', 'facil', 'astronomia'),
('l3', 'L', 'Bebida blanca que dan las vacas', 'Leche', 'facil', 'comida'),
('l7', 'L', 'Estructura de caminos complicados diseñada para confundir', 'Laberinto', 'medio', 'general'),
('dif-l1', 'L', 'Coordenada geográfica que indica la distancia al ecuador', 'Latitud', 'dificil', 'geografia'),
('m1', 'M', 'Fruto del manzano', 'Manzana', 'facil', 'comida'),
('m2', 'M', 'Futbolista argentino apodado ''La Pulga''', 'Messi', 'medio', 'deportes'),
('m3', 'M', 'Videojuego de construcción con bloques', 'Minecraft', 'facil', 'tecnologia'),
('dif-m1', 'M', 'Orgánulo celular encargado de producir energía', 'Mitocondria', 'dificil', 'biologia'),
('n1', 'N', 'Masa de vapor de agua suspendida en la atmósfera', 'Nube', 'facil', 'naturaleza'),
('n2', 'N', 'Órgano del olfato', 'Nariz', 'facil', 'anatomia'),
('n3', 'N', 'Plataforma de streaming de series y películas', 'Netflix', 'facil', 'tecnologia'),
('dif-n1', 'N', 'Gas que compone la mayor parte del aire', 'Nitrógeno', 'dificil', 'quimica'),
('o1', 'O', 'Órgano de los sentidos para oír', 'Oído', 'facil', 'anatomia'),
('o2', 'O', 'Capital de Noruega', 'Oslo', 'medio', 'geografia'),
('o3', 'O', 'Órganos de la vista', 'Ojos', 'facil', 'anatomia'),
('dif-o1', 'O', 'Trayectoria que sigue un cuerpo alrededor de otro por gravedad', 'Órbita', 'dificil', 'astronomia'),
('p1', 'P', 'Instrumento musical de teclas', 'Piano', 'medio', 'musica'),
('p2', 'P', 'Animal doméstico fiel al hombre', 'Perro', 'facil', 'animales'),
('p3', 'P', 'Comida italiana hecha con masa, salsa y queso', 'Pizza', 'facil', 'comida'),
('dif-p1', 'P', 'Supercontinente que existió hace cientos de millones de años', 'Pangea', 'dificil', 'geologia'),
('q1', 'Q', 'Ciencia que estudia las sustancias', 'Química', 'medio', 'ciencia'),
('q2', 'Q', 'Producto lácteo para untar', 'Queso', 'facil', 'comida'),
('q3', 'Q', 'Capital de Ecuador', 'Quito', 'medio', 'geografia'),
('dif-q1', 'Q', 'Número mínimo de miembros necesarios para sesionar', 'Quórum', 'dificil', 'derecho'),
('r1', 'R', 'Animal roedor pequeño', 'Ratón', 'facil', 'animales'),
('r2', 'R', 'Corriente de agua natural', 'Río', 'facil', 'naturaleza'),
('r3', 'R', 'Capital de Italia', 'Roma', 'medio', 'geografia'),
('dif-r1', 'R', 'Energía que se propaga en forma de ondas o partículas', 'Radiación', 'dificil', 'fisica'),
('s1', 'S', 'Astro que da luz y calor', 'Sol', 'facil', 'astronomia'),
('s2', 'S', 'Reptil que reptan sin patas', 'Serpiente', 'facil', 'animales'),
('s3', 'S', 'Servicio de música en streaming', 'Spotify', 'facil', 'tecnologia'),
('dif-s1', 'S', 'Conexión funcional entre neuronas para transmitir señales', 'Sinapsis', 'dificil', 'biologia'),
('t1', 'T', 'Medio de transporte sobre rieles', 'Tren', 'facil', 'general'),
('t2', 'T', 'Capital de Japón', 'Tokio', 'medio', 'geografia'),
('t3', 'T', 'Animal felino con rayas', 'Tigre', 'facil', 'animales'),
('dif-t1', 'T', 'Instrumento que mide la temperatura', 'Termómetro', 'dificil', 'instrumentos'),
('u1', 'U', 'Vestimenta igual para todos en un grupo', 'Uniforme', 'facil', 'vestimenta'),
('u2', 'U', 'Fruta morada en racimos', 'Uva', 'facil', 'comida'),
('u3', 'U', 'Servicio de transporte por aplicación', 'Uber', 'facil', 'tecnologia'),
('dif-u1', 'U', 'Tipo de radiación electromagnética más energética que la luz violeta', 'Ultravioleta', 'dificil', 'fisica'),
('v1', 'V', 'Animal que da leche', 'Vaca', 'facil', 'animales'),
('v2', 'V', 'Bebida alcohólica hecha de uvas', 'Vino', 'facil', 'comida'),
('v3', 'V', 'Deporte de pelota con red alta', 'Voleibol', 'medio', 'deportes'),
('dif-v1', 'V', 'Sustancia que estimula defensas para prevenir enfermedades', 'Vacuna', 'dificil', 'medicina'),
('w1', 'W', 'Bebida alcohólica destilada de cereales', 'Whisky', 'medio', 'bebidas'),
('w2', 'W', 'Red informática mundial', 'Web', 'facil', 'tecnologia'),
('w3', 'W', 'Aplicación de mensajería para teléfonos', 'WhatsApp', 'facil', 'tecnologia'),
('dif-w1', 'W', 'Tecnología que permite conexión inalámbrica a internet', 'Wifi', 'dificil', 'tecnologia'),
('x1', 'X', 'Instrumento musical de percusión', 'Xilófono', 'medio', 'musica'),
('x2', 'X', 'Consola de videojuegos de Microsoft', 'Xbox', 'medio', 'tecnologia'),
('dif-x1', 'X', 'Elemento químico noble usado en lámparas y flashes', 'Xenón', 'dificil', 'quimica'),
('y1', 'Y', 'Plataforma de videos en línea más utilizada', 'YouTube', 'facil', 'tecnologia'),
('y2', 'Y', 'Embarcación de recreo', 'Yate', 'medio', 'nautica'),
('y3', 'Y', 'Parte central del huevo', 'Yema', 'medio', 'comida'),
('dif-y1', 'Y', 'Elemento químico usado como antiséptico y en la tiroides', 'Yodo', 'dificil', 'quimica'),
('z1', 'Z', 'Plataforma de videollamadas muy usada en pandemia', 'Zoom', 'facil', 'tecnologia'),
('z2', 'Z', 'Calzado que cubre el pie', 'Zapato', 'facil', 'vestimenta'),
('z3', 'Z', 'Lugar donde se exhiben animales', 'Zoológico', 'medio', 'lugares'),
('dif-z1', 'Z', 'Rama de la biología que estudia a los animales', 'Zoología', 'dificil', 'biologia');
